objects/Account.object
<CustomObject>
    <fields>
        <fullName>FinServ__ReferredByContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>External Referrer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Referrals</relationshipLabel>
        <relationshipName>AccountContactReferrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__TotalBankDeposits__c</fullName>
        <description>Value of all banking deposit accounts.</description>
        <formula>FinServ__TotalBankDepositsJointOwner__c + FinServ__TotalBankDepositsPrimaryOwner__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Bank Deposits</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FinServ__TotalOutstandingCredit__c</fullName>
        <description>Value of client&apos;s total outstanding credit from the financial accounts that are managed by our firm.</description>
        <formula>FinServ__TotalOutstandingCreditPrimaryOwner__c + FinServ__TotalOutstandingCreditJointOwner__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Outstanding Credit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <fields>
        <fullName>FinServ__Household__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Household that this financial account rolls up to.</description>
        <label>Household</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Household</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Household Financial Accounts</relationshipLabel>
        <relationshipName>HouseholdFinancialAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>FinServ__FinancialAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Account</label>
        <referenceTo>FinServ__FinancialAccount__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__Household__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Household</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Household Opportunities</relationshipLabel>
        <relationshipName>HouseholdOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__ReferredByContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>External Referrer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>My Referrals</relationshipLabel>
        <relationshipName>OpportunityContactReferrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>OPP_nCino_Opportunity</fullName>
        <active>true</active>
        <businessProcess>nCino Loan</businessProcess>
        <description>Select for a New Loan (nCino) Opportunity</description>
        <label>Loan</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Treasury_Goals__c.object
<CustomObject>
    <fields>
        <fullName>TM_Fiscal_Year__c</fullName>
        <label>Fiscal Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
                <value>
                    <fullName>2026</fullName>
                </value>
                <value>
                    <fullName>2027</fullName>
                </value>
                <value>
                    <fullName>2028</fullName>
                </value>
                <value>
                    <fullName>2029</fullName>
                </value>
                <value>
                    <fullName>2030</fullName>
                </value>
                <value>
                    <fullName>2031</fullName>
                </value>
                <value>
                    <fullName>2032</fullName>
                </value>
                <value>
                    <fullName>2033</fullName>
                </value>
                <value>
                    <fullName>2034</fullName>
                </value>
                <value>
                    <fullName>2035</fullName>
                </value>
                <value>
                    <fullName>2036</fullName>
                </value>
                <value>
                    <fullName>2037</fullName>
                </value>
                <value>
                    <fullName>2038</fullName>
                </value>
                <value>
                    <fullName>2039</fullName>
                </value>
                <value>
                    <fullName>2040</fullName>
                </value>
                <value>
                    <fullName>2041</fullName>
                </value>
                <value>
                    <fullName>2042</fullName>
                </value>
                <value>
                    <fullName>2043</fullName>
                </value>
                <value>
                    <fullName>2044</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TM_New_Commercial_Relationships_Till__c</fullName>
        <label>New Commercial Relationships Till Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TM_New_Core_Treasury_Products_Sold_Till__c</fullName>
        <label>Core Treasury Products Sold Till Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TM_New_Money_Commercial_Deposit_s__c</fullName>
        <label>Deposit New Money Goal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TM_New_Money_Till_Date__c</fullName>
        <label>New Money Till Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TM_Treasury_Solutions_Officer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Treasury Sales Officer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Treasury_Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TM_of_New_Commercial_Relationships__c</fullName>
        <label>New Commercial Relationships Goal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TM_of_New_Core_Treasury_Products_Sold__c</fullName>
        <label>Core Treasury Products Sold Goal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Treasury Goals</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Treasury Goals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Treasury Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Commercial_RMHomeHeaderControllerTest.cls
/*********************************************************************************************************
*@author             : PwC Team
*@date               : 
*@description        : This class covers the controller class "Commercial_RMHomeHeaderController" 
*@Modification Log   :
Change History Story              Modify by               Date                          Desc
**********************************************************************************************************/

@isTest(SeeAllData=FALSE)
private class Commercial_RMHomeHeaderControllerTest{
    private static String accRecordTypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByDeveloperName().get('IndustriesBusiness').getRecordTypeId();
    /********************************************************************************************************
Method name : setupTestData
Parameters  : none
return      : void
**********************************************************************************************************/
    @testSetup
    static void setupTestData(){
        test.startTest();
        //fetch the Mortgage recordtype id from Opportunity object
        Id MortgageRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('OPP_nCino_Opportunity').getRecordTypeId();
        //RecordType rtName= [select name,id,developerName from RecordType WHERE developerName ='Mortgage' LIMIT 1];
        Opportunity opportunity_Obj = new Opportunity( RecordTypeId = MortgageRecordTypeId,IsPrivate = false, Name = 'Name662', Description = '7',
                                                      StageName = 'Prospecting', Probability = 10, CloseDate = Date.today(), 
                                                      Type = 'Existing Business', NextStep = 'NextStep764', 
                                                      LeadSource = 'Advertisement', ForecastCategoryName = 'Omitted', 
                                                      Pricebook2Id = Test.getStandardPricebookId());
        Insert opportunity_Obj; 
        
        Account accRecord = new Account();
        accRecord.Name = 'Test Account';
        accRecord.RecordTypeId = accRecordTypeId;
        Insert accRecord;
        
        test.stopTest();
    }
    
    /********************************************************************************************************
Method name : getRMopportunitiesTest
Parameters  : none
return      : void
purpose     : covers getRMopportunities
**********************************************************************************************************/
    static testMethod void getRMopportunitiesTest(){
        List<Account> accList  =  [SELECT Id,Name,FinServ__TotalBankDeposits__c,FinServ__TotalOutstandingCredit__c,ownerId
                                   FROM Account
                                   WHERE Id != null
                                  LIMIT 1];
        
        System.assertEquals(false,accList.size()==0);
        //query account records
        List<Opportunity> opportunity_Obj  =  [SELECT Id,AccountId,RecordTypeId,IsPrivate,Name,Description,StageName,
                                                Amount,Probability,ExpectedRevenue,CloseDate,Type,NextStep,LeadSource,
                                                IsClosed,IsWon,ForecastCategory,ForecastCategoryName,CampaignId,HasOpportunityLineItem,
                                                Pricebook2Id,CreatedDate,CreatedById,LastModifiedDate,LastModifiedById,SystemModstamp,
                                                LastActivityDate,FiscalQuarter,FiscalYear,Fiscal,
                                                LastViewedDate,LastReferencedDate,
                                                FinServ__FinancialAccount__c,FinServ__Household__c,
                                                FinServ__ReferredByContact__c
                                               FROM Opportunity
                                               WHERE Id != NULL
                                               LIMIT 1
                                              ];
        //assert
        System.assertEquals(false,opportunity_Obj.size()==0);
        Treasury_Goals__c goal = new Treasury_Goals__c(TM_of_New_Commercial_Relationships__c=10, TM_of_New_Core_Treasury_Products_Sold__c=10, TM_New_Money_Commercial_Deposit_s__c=10, TM_New_Money_Till_Date__c=10, TM_New_Commercial_Relationships_Till__c=10, TM_New_Core_Treasury_Products_Sold_Till__c=10, TM_Fiscal_Year__c='2022', TM_Treasury_Solutions_Officer__c = UserInfo.getUserId());
        insert goal;
        // Commercial Dev
        //Commercial_RMHomeHeaderController.getRMopportunities('Name','DESC');
    }
    
    /********************************************************************************************************
Method name : setAmountOnOppsTest
Parameters  : none
return      : void
purpose     : covers the lines with amount greater than 0
**********************************************************************************************************/
    
    static testMethod void setAmountOnOppsTest(){
        AggregateResult[]   accResults;
        List<Account> accList  =  [SELECT Id,Name,FinServ__TotalBankDeposits__c,FinServ__TotalOutstandingCredit__c,ownerId
                                   FROM Account
                                   WHERE Id != null
                                  ];
        accResults = [SELECT SUM(Account.FinServ__TotalBankDeposits__c)depositbalance,SUM(Account.FinServ__TotalOutstandingCredit__c)creditbalance FROM Account WHERE OwnerId =:Userinfo.getUserId()];
        //accResults[0].SUM(Account.FinServ__TotalBankDeposits__c)depositbalance = 1230;
        System.assertEquals(true,accList.size()>0);
        List<Opportunity> opportunity_Obj  =  [SELECT Id,AccountId,RecordTypeId,IsPrivate,Name,Description,StageName,
                                                Amount,Probability,ExpectedRevenue,CloseDate,Type,NextStep,LeadSource,
                                                IsClosed,IsWon,ForecastCategory,ForecastCategoryName,CampaignId,
                                                HasOpportunityLineItem,Pricebook2Id,CreatedDate,CreatedById,LastModifiedDate,
                                                LastModifiedById,SystemModstamp,LastActivityDate,FiscalQuarter,FiscalYear,Fiscal,
                                                LastViewedDate,LastReferencedDate,
                                                FinServ__FinancialAccount__c,FinServ__Household__c,FinServ__ReferredByContact__c
                                               FROM Opportunity
                                               WHERE Id != NULL
                                              ];
        opportunity_Obj[0].Amount = 9;
        update opportunity_Obj;

        System.assertEquals(true,opportunity_Obj.size()>0);
        // Commercial Dev
        //Commercial_RMHomeHeaderController.getRMopportunities('Name','DESC');
    }

    /********************************************************************************************************
Method name : setAmountOnOppsTest
Parameters  : none
return      : void
purpose     : covers the lines with amount greater than 0
**********************************************************************************************************/
    
static testMethod void setClosedAmountOnOppsTest(){
    AggregateResult[]   accResults;
    List<Account> accList  =  [SELECT Id,Name,FinServ__TotalBankDeposits__c,FinServ__TotalOutstandingCredit__c,ownerId
                               FROM Account
                               WHERE Id != null
                              ];
    accResults = [SELECT SUM(Account.FinServ__TotalBankDeposits__c)depositbalance,SUM(Account.FinServ__TotalOutstandingCredit__c)creditbalance FROM Account WHERE OwnerId =:Userinfo.getUserId()];
    //accResults[0].SUM(Account.FinServ__TotalBankDeposits__c)depositbalance = 1230;
    System.assertEquals(true,accList.size()>0);
    List<Opportunity> opportunity_Obj  =  [SELECT Id,AccountId,RecordTypeId,IsPrivate,Name,Description,StageName,
                                            Amount,Probability,ExpectedRevenue,CloseDate,Type,NextStep,LeadSource,
                                            IsClosed,IsWon,ForecastCategory,ForecastCategoryName,CampaignId,
                                            HasOpportunityLineItem,Pricebook2Id,CreatedDate,CreatedById,LastModifiedDate,
                                            LastModifiedById,SystemModstamp,LastActivityDate,FiscalQuarter,FiscalYear,Fiscal,
                                            LastViewedDate,LastReferencedDate,
                                            FinServ__FinancialAccount__c,FinServ__Household__c,FinServ__ReferredByContact__c
                                           FROM Opportunity
                                           WHERE Id != NULL
                                          ];
    opportunity_Obj[0].Amount = 9;
    opportunity_Obj[0].Stagename = 'Immplemation';
    update opportunity_Obj;

    System.assertEquals(true,opportunity_Obj.size()>0);
    // Commercial Dev
    //Commercial_RMHomeHeaderController.getRMopportunities('Name','DESC');
}
    
    /********************************************************************************************************
Method name : getRMOppsException
Parameters  : none
return      : void
purpose     : covers catch block
**********************************************************************************************************/
    static testMethod void getRMOppsException(){
        try{
            //query account records
        List<Account> accList  =  [SELECT Id,Name,FinServ__TotalBankDeposits__c,FinServ__TotalOutstandingCredit__c,ownerId
                                   FROM Account
                                   WHERE Id != null
                                   LIMIT 1
                                  ];

        System.assertEquals(true,accList.size()==1);
            //query opportunity records
        List<Opportunity> opportunity_Obj  =  [SELECT Id,AccountId,RecordTypeId,IsPrivate,Name,Description,StageName,
                                                Amount,Probability,ExpectedRevenue,CloseDate,Type,NextStep,LeadSource,
                                                IsClosed,IsWon,ForecastCategory,ForecastCategoryName,CampaignId,HasOpportunityLineItem,
                                                Pricebook2Id,CreatedDate,CreatedById,LastModifiedDate,LastModifiedById,SystemModstamp,LastActivityDate,FiscalQuarter,FiscalYear,Fiscal,
                                                LastViewedDate,LastReferencedDate,
                                                FinServ__FinancialAccount__c,FinServ__Household__c,FinServ__ReferredByContact__c 
                                               FROM Opportunity
                                              WHERE Id != NULL];
        System.assertEquals(true,opportunity_Obj.size()>0);
            // Commercial Dev
        Commercial_RMHomeHeaderController.getRMopportunities('','');
        }catch(Exception expt){
            //throw exception
            //throw new AuraHandledException(System.Label.TM_StdErrorMessage);
            //throw new AuraHandledException(expt.getMessage());
            System.assert(expt.getMessage()!=null);
        }
    }
    
}