objects/Account.object
<CustomObject>
    <fields>
        <fullName>CIF__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>CIF#</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FinServ__TotalBankDeposits__c</fullName>
        <description>Value of all banking deposit accounts.</description>
        <formula>FinServ__TotalBankDepositsJointOwner__c + FinServ__TotalBankDepositsPrimaryOwner__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Bank Deposits</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Relationship_Manager__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Relationship Manager</label>
        <length>85</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>nSBA__External_Credit_Score__c</fullName>
        <description>External credit score returned for this business.</description>
        <inlineHelpText>External credit score returned for this business.</inlineHelpText>
        <label>External Credit Score</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>CIF__c</fullName>
        <formula>Account.CIF__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates to this field must be done on the Account record</inlineHelpText>
        <label>CIF#</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship_Manager__c</fullName>
        <formula>Account.Owner.FirstName &amp;&quot;,&quot;&amp; Account.Owner.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>&quot;Account Owner&quot; listed for the relationship account</inlineHelpText>
        <label>Relationship Manager</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/LLC_BI__Loan__c.object
<CustomObject>
    <description>The Loan Object stores information of the details of a Loan.</description>
    <fields>
        <fullName>LLC_BI__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is required. It is automatically populated during loan creation. This field is a lookup to a relationship/account that the loan is associated to and denotes the primary borrower for the loan.</description>
        <label>Relationship</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LLC_BI__Amount__c</fullName>
        <description>This field is required. It is manually populated. It contains the full original amount of the Loan; this is the amount of the Loan at the time it was booked. This value should not change over time and is consistent over installment and line of credit products. This is used to calculate exposure for Line of Credit Products.</description>
        <inlineHelpText>This field is the &quot;Original Amount&quot; of the loan at the time of underwriting. This is different than the &quot;Principal Balance&quot; of the loan, which is the balance of the loan today.</inlineHelpText>
        <label>Original Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LLC_BI__Stage__c</fullName>
        <description>This field may be manually populated or by workflow, depending on the institution. It is used to specify a loan&apos;s current approval stage in the loan lifecycle. This information is used to drive several processes and features in the nCino system.</description>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Qualification / Proposal</fullName>
                </value>
                <value>
                    <fullName>Application Processing</fullName>
                </value>
                <value>
                    <fullName>Credit Underwriting</fullName>
                </value>
                <value>
                    <fullName>Credit Decisioning</fullName>
                </value>
                <value>
                    <fullName>Pre-Closing Due Diligence</fullName>
                </value>
                <value>
                    <fullName>Doc Prep &amp; Review</fullName>
                </value>
                <value>
                    <fullName>Closing</fullName>
                </value>
                <value>
                    <fullName>Booking / Funding</fullName>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Loan</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>LLC_BI__Loan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is automatically populated when the opportunity is converted to a loan. This field captures the loan record that the opportunity was converted to. Linking the opportunity to the product that was converted.</description>
        <label>Converted Opportunity</label>
        <referenceTo>LLC_BI__Loan__c</referenceTo>
        <relationshipLabel>Converted Opportunity</relationshipLabel>
        <relationshipName>ConvertedOpportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Loan_Amount__c</fullName>
        <inlineHelpText>Expected Loan Amount</inlineHelpText>
        <label>Loan Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TM_Anticipated_Deposit_Amount__c</fullName>
        <label>Anticipated Deposit Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TM_New_Money__c</fullName>
        <label>New Money</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TM_Projected_Annual_Treasury_Fee_Income__c</fullName>
        <label>Projected First Year Treasury Fee Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Treasury_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Treasury Products</relationshipLabel>
        <relationshipName>Treasury_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Treasury Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Treasury Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Treasury Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TM_AccountPageController.cls
/*********************************************************************************************************
*@author    : PwC Team
*@date      : April 30th 2020
*@description : This class used in lightning component - 
*@Modification Log   :
Change History Story              Modify by               Date                          Desc
**********************************************************************************************************/
public without sharing class TM_AccountPageController {

    /*********************************************************************************************************
    /* Method Name : getAccountDetails
    * param : accountId
    *purpose :
    **********************************************************************************************************/
    //get account details for header
    @auraEnabled
    public static AccountWrapper getAccountDetails(Id accountId){
        try{
            // Integer totalOpenCases = 0;
            Decimal totalBankDeposits = 0;
            Integer totalProducts = 0;
            Decimal totalLoans = 0;
            Decimal totalDeposits = 0;
            Decimal totalTreasury = 0;
            Decimal loanAmount = 0;
            String address = '';
            Decimal annualRevenue = 0;
            
            // account info
            Account account = [SELECT Id,RecordTypeId, Name, Industry, AnnualRevenue, FinServ__TotalBankDeposits__c, Phone, BillingStreet, BillingCity, BillingState, BillingPostalCode, BillingCountry,Website,OwnerId,Account.Owner.Name, CIF__c, nSBA__External_Credit_Score__c,Relationship_Manager__c FROM Account WHERE Id =: accountId]; 

            // sum of Loan amount
            AggregateResult[] groupedLoans = [SELECT SUM(LLC_BI__Amount__c)sumOfLoan FROM LLC_BI__Loan__c WHERE LLC_BI__Account__c =:accountId AND LLC_BI__Stage__c = 'Booked'];
            totalLoans = groupedLoans[0].get('sumOfLoan') == null ? 0 : (Decimal)groupedLoans[0].get('sumOfLoan');
            totalLoans = totalLoans.divide(1000000, 2);

            // count of Open cases
            // AggregateResult[] groupedCases = [SELECT Count(Id)casesCount FROM Case WHERE AccountId =:accountId AND Status != 'Closed'];
            // totalOpenCases = (Integer) groupedCases[0].get('casesCount');
            // totalOpenCases = totalOpenCases.divide(1000000, 2);

            //count of Treasury Products
            AggregateResult[] groupedproducts = [SELECT Count(Id)productCount FROM Treasury_Product__c WHERE Account_Name__c =:accountId];
            totalProducts = (Integer) groupedproducts[0].get('productCount');

            // RecordType=[SELECT Name FROM RecordType WHERE Id=:account.RecordTypeId].Name;     
            if (account.BillingStreet != null) {
                address = account.BillingStreet + ' ';
            }
            if (account.BillingCity != null) {
                address += account.BillingCity+' ';
            }
            if (account.BillingState != null) {
                address += account.BillingState + ' ';
            }
            if (account.BillingPostalCode != null) {
                address += account.BillingPostalCode;
            }
            
            //if annual revenue is not null
            if(account.AnnualRevenue !=null) {
                annualRevenue= (account.AnnualRevenue)/1000000;
            }   

            //if Total Bank Deposits is not null
            if(account.FinServ__TotalBankDeposits__c !=null) {
                totalBankDeposits = (account.FinServ__TotalBankDeposits__c)/1000000;
            }      
            
            List<Opportunity> opportunityList = [SELECT Id, StageName, TM_Anticipated_Deposit_Amount__c, TM_Projected_Annual_Treasury_Fee_Income__c, TM_New_Money__c, Loan_Amount__c, RecordType.Name FROM Opportunity WHERE AccountId = :accountId];            
            for(Opportunity opp:opportunityList){
                if (opp.RecordType.Name == 'Loan' && opp.Loan_Amount__c != null && opp.StageName == 'Closed Won') {
                    // totalLoans += opp.Loan_Amount__c;
                    // if (opp.StageName == 'Closed Won') {
                    loanAmount += opp.Loan_Amount__c;
                    // }
                }else if (opp.RecordType.Name == 'Track Deposit Pipeline' && opp.TM_Anticipated_Deposit_Amount__c != null) {
                    totalDeposits += opp.TM_Anticipated_Deposit_Amount__c;
                }else if (opp.RecordType.Name == 'Track Treasury Products Sold' && opp.TM_Projected_Annual_Treasury_Fee_Income__c != null) {
                    totalTreasury += opp.TM_Projected_Annual_Treasury_Fee_Income__c;
                }
            }
            
            totalDeposits = totalDeposits.divide(1000000, 2);
            totalTreasury = totalTreasury.divide(1000000, 2);
            loanAmount = loanAmount.divide(1000000, 2);
            // outstandingOppty = outstandingOppty.divide(1000000, 2);
            AccountWrapper aw = new AccountWrapper(account, totalBankDeposits, totalLoans, address, annualRevenue, totalDeposits, totalTreasury, loanAmount, totalProducts);
            return aw;
        }catch(Exception expt){
            // throw exception
            throw new AuraHandledException(System.Label.TM_StdErrorMessage);
        }   
    }
    
    //Account Wrapper
    public class AccountWrapper{
        @AuraEnabled public Account acc;
        // @AuraEnabled public Integer totalOpenCases;
        @AuraEnabled public Decimal totalBankDeposits;
        @AuraEnabled public Decimal totalLoans;
        // @AuraEnabled public Decimal outstandingOppty;
        // @AuraEnabled public Decimal roec;
        @auraEnabled public String address;
        @AuraEnabled public Decimal annualRevenue;
        @AuraEnabled public Decimal totalDeposits;
        @AuraEnabled public Decimal totalTreasury;
        @AuraEnabled public Decimal loanAmount;
        @AuraEnabled public Integer totalTreasuryProducts;
        
        /**
         * @description AccountWrapper description
         * @param  acc                   acc description
         * @param  totalBankDeposits        totalBankDeposits description
         * @param  totalLoans            totalLoans description
         * @param  address               address description
         * @param  annualRevenue         annualRevenue description
         * @param  totalDeposits         totalDeposits description
         * @param  totalTreasury         totalTreasury description
         * @param  loanAmount            loanAmount description
         * @param  totalTreasuryProducts totalTreasuryProducts description
         * @return                       return description
         */ 
        public AccountWrapper(Account acc, Decimal totalBankDeposits, Decimal totalLoans, String address, Decimal annualRevenue, Decimal totalDeposits, Decimal totalTreasury, Decimal loanAmount, Integer totalTreasuryProducts){
            // this.WonOppFYTD=WonOppFYTD;            
            // this.RecordType=RecordType;
            // this.Executive=Executive;
            this.acc = acc;
            // this.totalOpenCases = totalOpenCases;
            this.totalBankDeposits = totalBankDeposits;
            this.totalLoans = totalLoans;
            // this.outstandingOppty = outstandingOppty;
            // this.roec = roec;
            this.address = address;
            this.annualRevenue = annualRevenue;
            this.totalDeposits = totalDeposits;
            this.totalTreasury = totalTreasury;
            this.loanAmount = loanAmount;
            this.totalTreasuryProducts = totalTreasuryProducts;
        }
    }
}