objects/CM_EtranConfigurationSetting__mdt.object
<CustomObject>
    <description>CLOS - This is used to store all the configuration related to ETRAN SBA Integration</description>
    <fields>
        <fullName>TECH_CLSPassword__c</fullName>
        <label>TECH_CLSPassword</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TECH_CLSPin__c</fullName>
        <label>TECH_CLSPin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TECH_CLSUsername__c</fullName>
        <label>TECH_CLSUsername</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TECH_Email__c</fullName>
        <label>TECH_Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TECH_Endpoint__c</fullName>
        <label>TECH_Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TECH_LocationId__c</fullName>
        <label>TECH_LocationId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TECH_SoftwareVendorCode__c</fullName>
        <label>TECH_SoftwareVendorCode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TECH_SoftwareVendorName__c</fullName>
        <label>TECH_SoftwareVendorName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Etran Configuration Setting</label>
    <pluralLabel>Etran Configuration Settings</pluralLabel>
</CustomObject>

objects/EtranCredential__c.object
<CustomObject>
    <fields>
        <fullName>TECH_CLSPassword__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>TECH CLSPassword</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TECH_CLSPin__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>TECH CLSPin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TECH_CLSUsername__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>TECH CLSUsername</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TECH_SFUsername__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>TECH SFUsername</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>EtranCredential</label>
    <nameField>
        <displayFormat>EtranCredential - {000000000}</displayFormat>
        <label>EtranCredential Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EtranCredentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/LLC_BI__Application__c.object
<CustomObject>
    <description>The Application object is used to capture entry details about a relationship&apos;s business (loans and deposits) with the financial institution. The object is primarily used in the nCino SBA Package.</description>
    <fields>
        <fullName>nSBA__Application_Number__c</fullName>
        <description>Application Number assigned by the lender.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Application Number assigned by the lender.</inlineHelpText>
        <label>Application Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>Application-{00000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/LLC_BI__Loan__c.object
<CustomObject>
    <description>The Loan Object stores information of the details of a Loan.</description>
    <fields>
        <fullName>LLC_BI__Amount__c</fullName>
        <description>This field is required. It is manually populated. It contains the full original amount of the Loan; this is the amount of the Loan at the time it was booked. This value should not change over time and is consistent over installment and line of credit products. This is used to calculate exposure for Line of Credit Products.</description>
        <inlineHelpText>This field is the &quot;Original Amount&quot; of the loan at the time of underwriting. This is different than the &quot;Principal Balance&quot; of the loan, which is the balance of the loan today.</inlineHelpText>
        <label>Original Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LLC_BI__Application__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is optional. It is automatically populated. This lookup field is used to specify the application record that is associated to the loan and is used as part of the SBA process and Customer Portal.</description>
        <label>Application</label>
        <referenceTo>LLC_BI__Application__c</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Loan</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/WS_eTranApplicationWithdraw.cls
/** 
 * This is Cancel Loan Application class
 * Date               User               Change 
 * 8/20/2021          PwC               Initial Version
 * 
 * This class makes eTran call to cancel the loan application generated without having the loan number
*/
public with sharing class WS_eTranApplicationWithdraw {

    @InvocableMethod(label='eTranApplicationWithdraw')
    public static list<WS_eTranServiceInvocableResponse> cancelApplicationCallout (list<WS_eTranServiceInvocableRequest> inputVar) {
        input = inputVar[0];
        getStatusCallout(input, output);
        return new list<WS_eTranServiceInvocableResponse> {output};
    }
    
    // INPUT VARS
    public static WS_eTranServiceInvocableRequest input;
    // OUTPUT VARS
    public static WS_eTranServiceInvocableResponse output = new WS_eTranServiceInvocableResponse();
    
    public class etranApplicationWithdraw {
        public String MethodNamePhysical;
        public String CLSUsername;
        public String CLSPassword;
        public String CLSPIN;
        public String SoftwareVendorCode;
        public String SoftwareVendorName;
        public String ApplicationNumber;
        public String Email;
        public String LocationId;
        public String RequestedAmount;
        public etranApplicationWithdraw(CM_EtranConfigurationSetting__mdt metadata, EtranCredential__c cred, LLC_BI__Application__c app, LLC_BI__Loan__c loan ){
            MethodNamePhysical = 'OrigWithdraw';
            CLSUsername = cred.TECH_CLSUsername__c;
            CLSPassword = cred.TECH_CLSPassword__c;
            CLSPIN = cred.TECH_CLSPin__c;
            SoftwareVendorCode = metadata.TECH_SoftwareVendorCode__c;
            SoftwareVendorName = metadata.TECH_SoftwareVendorName__c;
            ApplicationNumber = app.nSBA__Application_Number__c;
            Email = metadata.TECH_Email__c;
            LocationId = metadata.TECH_LocationId__c;
            RequestedAmount = String.valueOf(loan.LLC_BI__Amount__c);
            
        }
    }
    
    public class etranStatusResponse {
    	public String ErrorMessageTechnical;
        public String PasswordUpdateRequired;
        public String ErrorMessageEnglish;
        public String ResponseData;
    }

    public static WS_eTranServiceInvocableResponse getStatusCallout(WS_eTranServiceInvocableRequest input, 
                                                                        WS_eTranServiceInvocableResponse output){
        CM_EtranConfigurationSetting__mdt metadata = [SELECT TECH_Endpoint__c, TECH_SoftwareVendorName__c, TECH_SoftwareVendorCode__c, TECH_LocationId__c, TECH_Email__c
                                                            FROM CM_EtranConfigurationSetting__mdt WHERE DeveloperName = 'eTran_Configuration' LIMIT 1 ];
        
       	EtranCredential__c cred = [SELECT Id, TECH_CLSUsername__c, TECH_CLSPassword__c, TECH_CLSPin__c
            	                         FROM EtranCredential__c  WHERE TECH_SFUsername__c =: Userinfo.getUserName() LIMIT 1];
        
        LLC_BI__Application__c application = [SELECT Id, nSBA__Application_Number__c 
                                                    FROM LLC_BI__Application__c WHERE Id =: input.appId];

        LLC_BI__Loan__c loanRecord = [SELECT Id, LLC_BI__Amount__c FROM LLC_BI__Loan__c 
                                                WHERE LLC_BI__Application__c =: input.appId ];                                           

        String endpoint = metadata.TECH_Endpoint__c;

		etranApplicationWithdraw requestWrapper = new etranApplicationWithdraw(metadata,cred,application, loanRecord );
        String requestBody = JSON.serialize(requestWrapper);
                                                                            
        Http http = new Http();
        HttpRequest req = new HttpRequest();
        req.setTimeout(120000);
        req.setMethod('POST');
        req.setEndpoint(endpoint);
        req.setHeader('CONTENT-TYPE','application/json');
        req.setHeader('ACCEPT','application/json');
        req.setHeader('CONNECTION','close');
        req.setHeader('VERSION','HTTP/1.1');
        req.setBody(requestBody);
        system.debug('##request:'+req.getBody());
        HttpResponse response = http.send(req);
        system.debug('##Response'+response);
        if (response.getStatusCode() == 200) {
            system.debug('##Response:'+response.getBody());
        	etranStatusResponse responseWrapper = (etranStatusResponse)JSON.deserialize(response.getBody(), etranStatusResponse.class);
            if(String.isNotBlank(responseWrapper.ErrorMessageTechnical)){
                output.errors = responseWrapper.ErrorMessageTechnical;
            }else{
                output.LoanApplicationStatus = parseXMLResponse(responseWrapper.ResponseData);
            }
        }else{
                output.errors = response.getStatusCode() + ': ' + response.getStatus() + ' - ' + response.getBody();
            }
        return output; 
    }
    
    public static String parseXMLResponse(String xmlResp){
        Dom.Document doc = new Dom.Document();
        doc.load(xmlResp);
        //Retrieve the root element for this document.
        Dom.XMLNode address = doc.getRootElement();
        Dom.XMLNode App = address.getChildElement('App', null);
        Dom.XMLNode Results = App.getChildElement('Results', null);
        String LoanAppStatCd = Results.getChildElement('LoanAppStatCd', null).getText();
        return LoanAppStatCd;
    }
}