objects/CM_EtranConfigurationSetting__mdt.object
<CustomObject>
    <description>CLOS - This is used to store all the configuration related to ETRAN SBA Integration</description>
    <fields>
        <fullName>TECH_CLSPassword__c</fullName>
        <label>TECH_CLSPassword</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TECH_CLSPin__c</fullName>
        <label>TECH_CLSPin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TECH_CLSUsername__c</fullName>
        <label>TECH_CLSUsername</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TECH_Endpoint__c</fullName>
        <label>TECH_Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TECH_SoftwareVendorCode__c</fullName>
        <label>TECH_SoftwareVendorCode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TECH_SoftwareVendorName__c</fullName>
        <label>TECH_SoftwareVendorName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Etran Configuration Setting</label>
    <pluralLabel>Etran Configuration Settings</pluralLabel>
</CustomObject>

objects/EtranCredential__c.object
<CustomObject>
    <fields>
        <fullName>TECH_CLSPassword__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>TECH CLSPassword</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TECH_CLSPin__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>TECH CLSPin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TECH_CLSUsername__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>TECH CLSUsername</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TECH_SFUsername__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>TECH SFUsername</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>EtranCredential</label>
    <nameField>
        <displayFormat>EtranCredential - {000000000}</displayFormat>
        <label>EtranCredential Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EtranCredentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/LLC_BI__Application__c.object
<CustomObject>
    <description>The Application object is used to capture entry details about a relationship&apos;s business (loans and deposits) with the financial institution. The object is primarily used in the nCino SBA Package.</description>
    <fields>
        <fullName>nSBA__Application_Number__c</fullName>
        <description>Application Number assigned by the lender.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Application Number assigned by the lender.</inlineHelpText>
        <label>Application Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>nSBA__SBA_Date_Application_Received__c</fullName>
        <description>Date SBA received application</description>
        <encryptionScheme>None</encryptionScheme>
        <label>SBA Date Application Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>nSBA__SBA_Loan_Number__c</fullName>
        <description>SBA Loan Number</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>SBA Loan Number</inlineHelpText>
        <label>SBA Loan Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>Application-{00000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WS_BatchToGetLoanNumber.cls
/** 
 * Batch apex to fetch SBA Loan number from ETran 
 * Date               User               Change 
 * 8/20/2021          PwC               Initial Version
 * 
 * Fetches SBA Loan for the loans that have an application number and were submitted more than 7 days ago
*/
global class WS_BatchToGetLoanNumber implements Database.Batchable<sObject>, Database.AllowsCallouts{

    CM_EtranConfigurationSetting__mdt metadata = [SELECT TECH_Endpoint__c, TECH_SoftwareVendorName__c, TECH_SoftwareVendorCode__c FROM CM_EtranConfigurationSetting__mdt 
                                                  					WHERE DeveloperName = 'eTran_Configuration' LIMIT 1 ];

    EtranCredential__c eCreds = [SELECT Id, TECH_CLSPassword__c, TECH_CLSPin__c, TECH_CLSUsername__c, TECH_SFUsername__c FROM EtranCredential__c 
                                                                      WHERE TECH_SFUsername__c =: UserInfo.getUserName() LIMIT 1];
    	
    public String username = eCreds.TECH_CLSUsername__c;
    public String password = eCreds.TECH_CLSPassword__c;
    public String pin = eCreds.TECH_CLSPin__c;
    public String endpoint = metadata.TECH_Endpoint__c;
    public String vendorCode = metadata.TECH_SoftwareVendorCode__c;
    public String vendorName = metadata.TECH_SoftwareVendorName__c;

    public class WS_BatchRequestwrapper {
        public String CLSUsername;
        public String CLSPassword;
        public String CLSPIN;
        public String SoftwareVendorName;
        public String SoftwareVendorCode;
        public String MethodNamePhysical;
        public String ApplicationNumber;                               
        public WS_BatchRequestwrapper(String method,String UserName, String Password, String Pin, String SftVenName, String SftVenCode, String appNumber) {
            CLSUsername = UserName;
            CLSPassword = Password;
            CLSPIN = Pin;
            SoftwareVendorName = SftVenName;
            SoftwareVendorCode = SftVenCode;
            MethodNamePhysical = method; 
            ApplicationNumber  = appNumber;      
        }
    }

    global Database.QueryLocator start(Database.BatchableContext bc){
        String soqlQuery = 'SELECT Id, nSBA__Application_Number__c, nSBA__SBA_Loan_Number__c, nSBA__SBA_Date_Application_Received__c  FROM LLC_BI__Application__c WHERE nSBA__Application_Number__c !=null AND nSBA__SBA_Loan_Number__c  = null AND nSBA__SBA_Date_Application_Received__c < LAST_N_DAYS:7';
        return Database.getQueryLocator(soqlQuery);
    }

    global void execute(Database.BatchableContext bc, List<LLC_BI__Application__c> applicationRecs){
         for(LLC_BI__Application__c applicationobj : applicationRecs){
                    String Username = username;
                    String Password = password;
                    String Pin = pin;
                    String Method = 'OriginateStatus';
                    String SoftwareVendorCode = vendorCode;
                    String SoftwareVendorName = vendorName;
                    String applicationNumber = applicationobj.nSBA__Application_Number__c;
                    
                    WS_BatchRequestwrapper reqWrapper = new WS_BatchRequestwrapper(Method, Username, Password, Pin, SoftwareVendorName, SoftwareVendorCode, applicationNumber);
                    String requestBody = JSON.serialize(reqWrapper);
                    system.debug('##requestBody'+requestBody);
                    
                    Http http = new Http();
                    HttpRequest req = new HttpRequest();
                    
                    req.setTimeout(120000);
                    req.setMethod('POST');
                    req.setEndpoint(endpoint);
                    req.setHeader('CONTENT-TYPE','application/json');
                    req.setHeader('Accept','application/json');
                    req.setHeader('CONNECTION','close');
                    req.setHeader('VERSION','HTTP/1.1');
                    req.setBody(requestBody);
                    HttpResponse response = http.send(req);
					system.debug('##response'+response);
                    WS_BatchToGetLoanNumberHelper.parseResponseBody(response, applicationobj.Id); 
        }
    }
    
    global void finish(Database.BatchableContext bc){
    }
}