objects/CM_EtranConfigurationSetting__mdt.object
<CustomObject>
    <description>CLOS - This is used to store all the configuration related to ETRAN SBA Integration</description>
    <fields>
        <fullName>TECH_Endpoint__c</fullName>
        <label>TECH_Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TECH_Timeout__c</fullName>
        <label>TECH_Timeout</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Etran Configuration Setting</label>
    <pluralLabel>Etran Configuration Settings</pluralLabel>
</CustomObject>

objects/ETran_Integration_Log__c.object
<CustomObject>
    <description>Log object to hold errors and synopses from the ETran PPP SBA Integration</description>
    <fields>
        <fullName>Application__c</fullName>
        <description>Application that this request was run against</description>
        <label>Application</label>
        <referenceTo>LLC_BI__Application__c</referenceTo>
        <relationshipLabel>ETran Integration Logs</relationshipLabel>
        <relationshipName>ETran_Integration_Logs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Error__c</fullName>
        <description>Errors returned by this integration call</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Error</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Synopsis__c</fullName>
        <description>Synopsis of this integration call</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Synopsis</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>ETran Integration Log</label>
    <nameField>
        <displayFormat>EIL-{000000}</displayFormat>
        <label>ETran Integration Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ETran Integration Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/WS_eTranService.cls
/** 
 * This is main eTran Service Class
 * Date               User               Change 
 * 8/20/2021          PwC               Initial Version
 * 
 * This class makes eTran call genearate application number and to update the loan applications
*/

public without sharing class WS_eTranService {
    
    // INPUT VARS
    public WS_eTranServiceInvocableRequest input;
    // OUTPUT VARS
    public WS_eTranServiceInvocableResponse output = new WS_eTranServiceInvocableResponse();
    //REQUEST VARS
    public String endpoint;
    public Integer timeout;
    public String requestBody;
    public HttpResponse response;
    
    public void preRequest() {
        CM_EtranConfigurationSetting__mdt metadata = WS_eTranServiceHelper.getMetadata();
        endpoint = metadata.TECH_Endpoint__c;
        timeout = Integer.valueOf(metadata.TECH_Timeout__c);
        requestBody = WS_eTranServiceHelper.createRequestBody(metadata, input, output);
    }
    
    public void request() {
        Http http = new Http();
        HttpRequest req = new HttpRequest();
        req.setTimeout(timeout);
        req.setMethod('POST');
        req.setEndpoint(endpoint);
        req.setHeader('CONTENT-TYPE','application/json');
        req.setHeader('ACCEPT','application/json');
        req.setHeader('CONNECTION','close');
        req.setHeader('VERSION','HTTP/1.1');
        req.setBody(requestBody);
        try {
            system.debug('req');
            response = http.send(req);
        } catch (Exception e) {
            output.errors = e.getTypeName() + ': ' + e.getMessage() + ' - ' + e.getStackTraceString();
        }
    }
    
    public void postRequest() {
        output = WS_eTranServiceHelper.parseResponseBody(response, output);
    }
    
    public void logDetails() {
        ETran_Integration_Log__c logs = new ETran_Integration_Log__c();
        logs.Application__c = this.input.appId;
        logs.Error__c = this.output.errors;
        logs.Synopsis__c = this.output.synopsis;
        insert logs;
    }
    
    public void main() {
        try {
            preRequest();
        } catch (Exception e) {
            output.errors += 'Exception in Pre Request: ' + e.getTypeName() + ': ' + e.getMessage() + ' | ' + e.getStackTraceString() + '\n\n';
        }
        if (String.isBlank(output.errors) || Test.isRunningTest()) {
            try {
                request();
            } catch (Exception e) {
                                   output.errors += 'Exception in Request: ' + e.getTypeName() + ': ' + e.getMessage() + ' | ' + e.getStackTraceString() + '\n\n';
                                  }
        }
        if (String.isBlank(output.errors) || Test.isRunningTest()) {
            try {
                postRequest();
            } catch (Exception e) {
                output.errors += 'Exception in Post Request: ' + e.getTypeName() + ': ' + e.getMessage() + ' | ' + e.getStackTraceString() + '\n\n';
            }
        }
        logDetails();
    }
}