objects/CO_Sweep_Setup__c.object
<CustomObject>
    <fields>
        <fullName>CF_Peg_Balance__c</fullName>
        <description>This field is used to store Peg Balance info.</description>
        <label>Peg Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CF_Primary_Child_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to store deposit account number info.</description>
        <label>Primary (Child) Account</label>
        <referenceTo>LLC_BI__Deposit__c</referenceTo>
        <relationshipLabel>Sweep Setup</relationshipLabel>
        <relationshipName>Sweep_Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CF_Secondary_Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to store Secondary Deposit Account info.</description>
        <label>Secondary (Parent) Account</label>
        <referenceTo>LLC_BI__Deposit__c</referenceTo>
        <relationshipLabel>Sweep Setup (Secondary (Parent) Account)</relationshipLabel>
        <relationshipName>Sweep_Setup1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sweep Setup</label>
    <nameField>
        <displayFormat>SSID-{000000}</displayFormat>
        <label>Sweep Service ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sweep Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/LLC_BI__Deposit__c.object
<CustomObject>
    <description>The Deposit Object is used to track details of a deposit within nCino</description>
    <label>Deposit</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Deposit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deposits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CT_TestClass_For_TS_Classes.cls
@isTest
public class CT_TestClass_For_TS_Classes {
/** 
* 8/18/2023 PwC - Jayanth - This test class should cover the TS Triggers inserted as part of ncino community instructions.
* 
*/
  
@TestSetup
    static voId makeData(){
        
        LLC_BI__Deposit__c vDep = new LLC_BI__Deposit__c(Name='Test Deposit');
        insert vDep;

        CO_Sweep_Setup__c vSweep = new CO_Sweep_Setup__c(CF_Primary_Child_Account__c = vDep.id,CF_Secondary_Parent_Account__c =vDep.Id ,CF_Peg_Balance__c = 55.00);
        insert vSweep;
		
    }
    
    @isTest
    public static voId testDeleteSweep() {
                     
        test.startTest();
       	CO_Sweep_Setup__c vSweepFind = [SELECT ID, CF_Peg_Balance__c FROM CO_Sweep_Setup__c WHERE CF_Peg_Balance__c = 55.00];
        system.assertEquals(55.00, vSweepFind.CF_Peg_Balance__c);   
		vSweepFind.CF_Peg_Balance__c = 66.00;
		delete vSweepFind;        
        test.stopTest();
    }    

}