objects/EtranCredential__c.object
<CustomObject>
    <fields>
        <fullName>TECH_CLSPassword__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>TECH CLSPassword</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TECH_CLSUsername__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>TECH CLSUsername</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TECH_SFUsername__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>TECH SFUsername</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>EtranCredential</label>
    <nameField>
        <displayFormat>EtranCredential - {000000000}</displayFormat>
        <label>EtranCredential Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EtranCredentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/LLC_BI__Application__c.object
<CustomObject>
    <description>The Application object is used to capture entry details about a relationship&apos;s business (loans and deposits) with the financial institution. The object is primarily used in the nCino SBA Package.</description>
    <fields>
        <fullName>nPortal__Artifact_Id__c</fullName>
        <description>This String holds the Id of the type of application which is getting created (i.e. Loan, Deposit, Treasury)</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This ID should match the artifact being created by the application</inlineHelpText>
        <label>Artifact Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>nSBA__Application_Number__c</fullName>
        <description>Application Number assigned by the lender.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Application Number assigned by the lender.</inlineHelpText>
        <label>Application Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>nSBA__SBA_Date_Application_Received__c</fullName>
        <description>Date SBA received application</description>
        <encryptionScheme>None</encryptionScheme>
        <label>SBA Date Application Received</label>
        <type>Date</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>Application-{00000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WS_BatchToGetLoanNumberTest.cls
/** 
 * This is get loan number Test class
 * Date               User               Change 
 * 8/20/2021          PwC               Initial Version
 * 
 * This is test class for WS_BatchToGetLoanNumber class.
*/
@isTest
public class WS_BatchToGetLoanNumberTest {
	  @TestSetup
    static voId makeData(){
        LLC_BI__Application__c application = new LLC_BI__Application__c(nPortal__Artifact_Id__c = 'eTran Application', nSBA__Application_Number__c ='33425543', nSBA__SBA_Date_Application_Received__c = (system.today()-10));
        insert application;
    }
    
    public class eTranStatusResponse implements HttpCalloutMock{
        public HttpResponse respond(HTTPRequest req){
            HttpResponse res = new HttpResponse();
            res.setStatus('Success');
            res.setStatusCode(200);
            res.setBody('{"ErrorMessageTechnical":"","PasswordUpdateRequired":"Unknown","ResponseData":"<?xml version=\\"1.0\\" encoding=\\"UTF-8\\"?>'+
						'<SBA_ETran_OrigStat_Response>'+
					'<AuthErrorNmb>0</AuthErrorNmb>'+
                    '<AuthErrorText>Login Successful</AuthErrorText>'+
					'<LoanAppStatus>In Review Reviewer 1</LoanAppStatus>'+ 
					'<LoanAppNmb>429643</LoanAppNmb>'+ 
					'<LoanAppNm>Business tue test</LoanAppNm>'+
					'<LoanAppRqstAmt>6000.00</LoanAppRqstAmt>'+
					'<LoanAppRecvDt>2021-08-19 06:35:57.0</LoanAppRecvDt>'+
					'<LoanAppAppvDt>2021-08-19 06:35:57.0</LoanAppAppvDt>'+
					'<LoanAppSBAAppvAmt>6000.00</LoanAppSBAAppvAmt>'+
					'<LoanNmb>88752652</LoanNmb>'+
					'<LoanGntyFeeAmt>450.00</LoanGntyFeeAmt>'+ 
					'<LoanAppFundDt></LoanAppFundDt>'+ 
					'<SBAOfcCd></SBAOfcCd>'+ 
					'<ZipCd5></ZipCd5>'+
					'</SBA_ETran_OrigStat_Response>","ErrorMessageEnglish":"Unknown"}');
            return res;
        }
    }
    
    public class eTranStatusResponseErrorMessageTech implements HttpCalloutMock{
        public HttpResponse respond(HTTPRequest req){
            HttpResponse res = new HttpResponse();
            res.setStatus('Success');
            res.setStatusCode(200);
            res.setBody('{"ErrorMessageTechnical":"PasswordUpdateRequired","PasswordUpdateRequired":"Unknown","ResponseData":"<?xml version=\\"1.0\\" encoding=\\"UTF-8\\"?>'+
						'<SBA_ETran_OrigStat_Response>'+
					'<AuthErrorNmb>0</AuthErrorNmb>'+
                    '<AuthErrorText>Login Successful</AuthErrorText>'+
					'<LoanAppStatus>In Review Reviewer 1</LoanAppStatus>'+ 
					'<LoanAppNmb>429643</LoanAppNmb>'+ 
					'<LoanAppNm>Business tue test</LoanAppNm>'+
					'<LoanAppRqstAmt>6000.00</LoanAppRqstAmt>'+
					'<LoanAppRecvDt>2021-08-19 06:35:57.0</LoanAppRecvDt>'+
					'<LoanAppAppvDt></LoanAppAppvDt>'+
					'<LoanAppSBAAppvAmt></LoanAppSBAAppvAmt>'+
					'<LoanNmb></LoanNmb>'+
					'<LoanGntyFeeAmt></LoanGntyFeeAmt>'+ 
					'<LoanAppFundDt></LoanAppFundDt>'+ 
					'<SBAOfcCd></SBAOfcCd>'+ 
					'<ZipCd5></ZipCd5>'+
					'</SBA_ETran_OrigStat_Response>","ErrorMessageEnglish":"Unknown"}');
            return res;
        }
    }
    
    @isTest
    public static voId testEtranLoanStatus() { 
        EtranCredential__c etran = new EtranCredential__c();
        etran.TECH_CLSUsername__c = 'TestUserName';
        etran.TECH_CLSPassword__c = 'TestPassword';
        etran.TECH_SFUsername__c = userinfo.getUserName();
        insert etran;
        system.assertEquals('TestUserName', etran.TECH_CLSUsername__c);
        LLC_BI__Application__c application = [SELECT Id FROM LLC_BI__Application__c LIMIT 1];
        test.startTest();
        Test.setMock(HttpCalloutMock.class, new eTranStatusResponse());
        WS_BatchToGetLoanNumberSchedular.getLoanNumber();
        WS_BatchToGetLoanNumber batch = new WS_BatchToGetLoanNumber();
        database.executebatch(batch, 1);
        test.stopTest();
    }
        @isTest
    public static voId testEtranLoanStatusError() { 
    	EtranCredential__c etran = new EtranCredential__c();
        etran.TECH_CLSUsername__c = 'TestUserName';
        etran.TECH_CLSPassword__c = 'TestPassword';
        etran.TECH_SFUsername__c = userinfo.getUserName();
        insert etran;
        system.assertEquals('TestUserName', etran.TECH_CLSUsername__c);
        LLC_BI__Application__c application = [SELECT Id FROM LLC_BI__Application__c LIMIT 1];
        test.startTest();
        Test.setMock(HttpCalloutMock.class, new eTranStatusResponseErrorMessageTech());
        WS_BatchToGetLoanNumberSchedular.getLoanNumber();
        WS_BatchToGetLoanNumber batch = new WS_BatchToGetLoanNumber();
        database.executebatch(batch, 1);
        test.stopTest();
	}
}