objects/nFORCE__System_Properties__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>A set of key-value pairs that can be used to set organization-wide parameters</description>
    <fields>
        <fullName>nFORCE__Category_Name__c</fullName>
        <description>The field is required. It indicates the category to which the system property belongs.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Category Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>nFORCE__Key__c</fullName>
        <description>The field is required. The combination of the category and the key is used to uniquely identify the system property.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>System Properties</label>
</CustomObject>

classes/csaLaserProMappingInstallerController.cls
public with sharing class csaLaserProMappingInstallerController {
  public class CheckInstall extends nFORCE.RemoteActionController.Endpoint {
    public override virtual Object invoke(Map<String, Object> params) {
      nFORCE.SystemProperties properties = nFORCE.SystemProperties.getInstance();
      return properties.getPropertyAsBoolean(
        nCSA_FRAME.csaConstants.CSASYSTEMPROPERTYCATEGORY,
        csaLaserProMappingConstants.PROPERTY_INSTALLEDKEY,
        false
      );
    }
  }

  public class Install extends nFORCE.RemoteActionController.Endpoint {
    public override virtual Object invoke(Map<String, Object> params) {
      List<sObject> toInsert = new List<sObject>();

      toInsert.add(
        nFORCE.SystemProperties.createProperty(
          nCSA_FRAME.csaConstants.CSASYSTEMPROPERTYCATEGORY,
          csaLaserProMappingConstants.PROPERTY_INSTALLEDKEY,
          csaLaserProMappingConstants.PROPERTY_INSTALLEDVALUE,
          true
        )
      );

      LLCLP.FormatManager.registerCustomFormatter(
        csaLaserProMappingController.class
      );

      insert toInsert;
      return null;
    }
  }

  public class Uninstall extends nFORCE.RemoteActionController.Endpoint {
    public override virtual Object invoke(Map<String, Object> params) {
      List<nFORCE__System_Properties__c> toDelete = new List<nFORCE__System_Properties__c>();

      toDelete.addAll(
        [
          SELECT Id
          FROM nFORCE__System_Properties__c
          WHERE
            nFORCE__Key__c = :csaLaserProMappingConstants.PROPERTY_INSTALLEDKEY
            OR nFORCE__Category_Name__c = :csaLaserProMappingConstants.PROERPTY_CATEGORY
          LIMIT 100
        ]
      );

      if (!toDelete.isEmpty()) {
        delete toDelete;
      }

      return null;
    }
  }
}