objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>TM_Anticipated_Deposit_Amount__c</fullName>
        <label>Anticipated Deposit Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TM_Projected_Annual_Treasury_Fee_Income__c</fullName>
        <label>Projected First Year Treasury Fee Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>TM_Track_Deposit_Pipeline</fullName>
        <active>true</active>
        <businessProcess>Track Deposit Pipeline</businessProcess>
        <description>Track Deposit Amounts</description>
        <label>Track Deposit Pipeline</label>
    </recordTypes>
    <recordTypes>
        <fullName>TM_Track_Treasury_Products_Sold</fullName>
        <active>true</active>
        <businessProcess>Track Treasury Products Sold</businessProcess>
        <description>Track Treasury Products &amp; Projected Fee Income</description>
        <label>Track Treasury Products Sold</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>TM_Order_Number__c</fullName>
        <label>Order Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TM_Product_Line__c</fullName>
        <description>Treasury Solutions</description>
        <label>Product Line</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Treasury Solutions</fullName>
                </value>
                <value>
                    <fullName>Business Deposits</fullName>
                </value>
                <value>
                    <fullName>Consumer Deposits</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TM_Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>TM_Product_Line__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Deposit Solutions</fullName>
                </value>
                <value>
                    <fullName>Management Solutions</fullName>
                </value>
                <value>
                    <fullName>Payable Solutions</fullName>
                </value>
                <value>
                    <fullName>Receivable Solutions</fullName>
                </value>
                <value>
                    <fullName>Liquidity Solutions</fullName>
                </value>
                <value>
                    <fullName>Fraud Solutions</fullName>
                </value>
                <value>
                    <fullName>Business Checking</fullName>
                </value>
                <value>
                    <fullName>Treasury Deposits</fullName>
                </value>
                <value>
                    <fullName>Contract Services</fullName>
                </value>
                <value>
                    <fullName>Public Funds</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Checking</fullName>
                </value>
                <value>
                    <fullName>Savings</fullName>
                </value>
                <value>
                    <fullName>CDs</fullName>
                </value>
                <value>
                    <fullName>IRAs</fullName>
                </value>
                <value>
                    <fullName>HSAs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TM_Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>TM_Product_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Commercial Checking</fullName>
                </value>
                <value>
                    <fullName>Community Checking</fullName>
                </value>
                <value>
                    <fullName>Small Business Checking</fullName>
                </value>
                <value>
                    <fullName>Public Funds Non-Interest Bearing Checking</fullName>
                </value>
                <value>
                    <fullName>Public Funds Interest Bearing Checking</fullName>
                </value>
                <value>
                    <fullName>CDARS</fullName>
                </value>
                <value>
                    <fullName>ICS</fullName>
                </value>
                <value>
                    <fullName>Repurchase Agreement</fullName>
                </value>
                <value>
                    <fullName>Multi User</fullName>
                </value>
                <value>
                    <fullName>EDI Addenda Translation</fullName>
                </value>
                <value>
                    <fullName>BAI File Download</fullName>
                </value>
                <value>
                    <fullName>BAI SFTP</fullName>
                </value>
                <value>
                    <fullName>ACH Origination</fullName>
                </value>
                <value>
                    <fullName>ACH Third Party Sender</fullName>
                </value>
                <value>
                    <fullName>Wire Transmission</fullName>
                </value>
                <value>
                    <fullName>Business BillPay</fullName>
                </value>
                <value>
                    <fullName>Credit Card Small Business</fullName>
                </value>
                <value>
                    <fullName>Credit Card Corporate</fullName>
                </value>
                <value>
                    <fullName>Credit Card Purchasing</fullName>
                </value>
                <value>
                    <fullName>RDC Low-Speed Scanner</fullName>
                </value>
                <value>
                    <fullName>RDC Hi-Speed Scanner</fullName>
                </value>
                <value>
                    <fullName>RDC Mobile</fullName>
                </value>
                <value>
                    <fullName>Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Payment Portal U-Pay</fullName>
                </value>
                <value>
                    <fullName>Payment Portal Autobooks</fullName>
                </value>
                <value>
                    <fullName>Payment Portal I-Collect</fullName>
                </value>
                <value>
                    <fullName>Lockbox Remote</fullName>
                </value>
                <value>
                    <fullName>Lockbox Retail</fullName>
                </value>
                <value>
                    <fullName>Lockbox Healthcare</fullName>
                </value>
                <value>
                    <fullName>Single Sweep</fullName>
                </value>
                <value>
                    <fullName>B1 - Small Business Checking</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TM_AddProductsControllerTest.cls
/**
 * @description test class for TM_AddProductsController description
 * 
 */ 
@isTest(SeeAllData=false)
public class TM_AddProductsControllerTest {
    // IndustriesBusiness Account Record Type
    private static String accRecordTypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByDeveloperName().get('IndustriesBusiness').getRecordTypeId();
    // TM_Track_Deposit_Pipeline Opportunity Record Type
    private static String depositRecordTypeId = Schema.getGlobalDescribe().get('Opportunity').getDescribe().getRecordTypeInfosByDeveloperName().get('TM_Track_Deposit_Pipeline').getRecordTypeId();
    // TM_Track_Treasury_Products_Sold Opportunity Record Type
    private static String treasuryRecordTypeId = Schema.getGlobalDescribe().get('Opportunity').getDescribe().getRecordTypeInfosByDeveloperName().get('TM_Track_Treasury_Products_Sold').getRecordTypeId();
    
    /**
     * @description setupTestData description
     * 
     */ 
    @testSetup
    static void setupTestData(){
        test.startTest();
        // insert acc record
        Account acc = new Account(Name = 'Smith', RecordTypeId = accRecordTypeId, BillingStreet = 'gumei', BillingCity = 'shanghai', BillingState = 'test', BillingPostalCode = '123', AnnualRevenue = 2000000);
        insert acc;
        // Pricebook2 price = new Pricebook2(Name = 'Standard Price Book', IsActive = true);
        // insert price;
        Id pricebookId = Test.getStandardPricebookId();
        // insert oppty records
        List<Opportunity> opps = new List<Opportunity>();
        Opportunity depositOpp = new Opportunity(Name = 'Smith Opportunity2',StageName = 'Closed Won',CloseDate = System.today(), AccountId = acc.Id, RecordTypeId = depositRecordTypeId, TM_Anticipated_Deposit_Amount__c = 2000000, Pricebook2Id = pricebookId);
        opps.add(depositOpp);
        Opportunity treasuryOpp = new Opportunity(Name = 'Smith Opportunity3',StageName = 'Closed Won',CloseDate = System.today(), AccountId = acc.Id, RecordTypeId = treasuryRecordTypeId, TM_Projected_Annual_Treasury_Fee_Income__c = 2000000);
        opps.add(treasuryOpp);
        insert opps;
        List<Product2> prods = new List<Product2>();
        Product2 prod1 = new Product2(Name = 'B1 - Small Business Checking', TM_Product_Line__c = 'Business Deposits', TM_Product_Type__c = 'Business Checking', TM_Product__c = 'B1 - Small Business Checking',TM_Order_Number__c=1);
        prods.add(prod1);
        Product2 prod2 = new Product2(Name = 'Multi User', TM_Product_Line__c = 'Treasury Solutions', TM_Product_Type__c = 'Management Solutions', TM_Product__c = 'Multi User',TM_Order_Number__c=1);
        prods.add(prod2);
        insert prods;
        List<PricebookEntry> entry = new List<PricebookEntry>();
        PricebookEntry entry1 = new PricebookEntry(IsActive = true, UnitPrice = 0, Product2Id = prod1.Id, Pricebook2Id = pricebookId);
        entry.add(entry1);
        PricebookEntry entry2 = new PricebookEntry(IsActive = true, UnitPrice = 0, Product2Id = prod2.Id, Pricebook2Id = pricebookId);
        entry.add(entry2);
        insert entry;
        test.stopTest();
    }

    static testMethod void testgetProductDetails(){
        test.StartTest();
        List<Product2> prod = [SELECT Id FROM Product2 WHERE Name = 'B1 - Small Business Checking'];
        System.assertEquals(true,prod.size()>0);
        List<OpportunityLineItem> oppItems = new List<OpportunityLineItem>();
        OpportunityLineItem oppItem = new OpportunityLineItem(UnitPrice = 0, ServiceDate = Date.today(), Description = 'SJLISNFSDLKSDJF', Quantity = 1, Product2Id = prod[0].Id);
        oppItems.add(oppItem);
        List<Opportunity> oppList  =  [SELECT Id from Opportunity WHERE RecordType.DeveloperName = 'TM_Track_Deposit_Pipeline'];
        System.assertEquals(true,oppList.size()>0);
        TM_AddProductsController.getProductDetails(oppList[0].Id);
        TM_AddProductsController.saveOpportunityItems(oppList[0].Id,oppItems);
        test.stopTest();
    }

    static testMethod void testgetOppDetails(){
        
        test.StartTest();
        List<Product2> prod = [SELECT Id FROM Product2 WHERE Name='Multi User'];
        System.assertEquals(true,prod.size()>0);
        List<OpportunityLineItem> oppItems = new List<OpportunityLineItem>();
        OpportunityLineItem oppItem = new OpportunityLineItem(UnitPrice = 0, ServiceDate = Date.today(), Description = 'SIENWELSDLFIN', Quantity = 1, Product2Id = prod[0].Id);
        oppItems.add(oppItem);
        List<Opportunity> oppList  =  [SELECT Id from Opportunity WHERE RecordType.DeveloperName = 'TM_Track_Treasury_Products_Sold'];
        System.assertEquals(true,oppList.size()>0);
        TM_AddProductsController.getProductDetails(oppList[0].Id);
        TM_AddProductsController.saveOpportunityItems(oppList[0].Id,oppItems);
        test.stopTest();
    }

    static testMethod void testgetOppDetails2(){
        
        test.StartTest();
        try {
            TM_AddProductsController.getProductDetails('0011');
        } catch (Exception expt) {
            System.assert(expt.getMessage()!=null);
        }
        test.stopTest();
    }
    static testMethod void testgetOppDetails3(){
        
        test.StartTest();
        try {
            TM_AddProductsController.saveOpportunityItems('0011',null);
        } catch (Exception expt) {
            System.assert(expt.getMessage()!=null);
        }
        test.stopTest();
    }

}