objects/Product2.object
<CustomObject>
    <fields>
        <fullName>TM_Order_Number__c</fullName>
        <label>Order Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TM_Product_Line__c</fullName>
        <description>Treasury Solutions</description>
        <label>Product Line</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Treasury Solutions</fullName>
                </value>
                <value>
                    <fullName>Business Deposits</fullName>
                </value>
                <value>
                    <fullName>Consumer Deposits</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TM_Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>TM_Product_Line__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Deposit Solutions</fullName>
                </value>
                <value>
                    <fullName>Management Solutions</fullName>
                </value>
                <value>
                    <fullName>Payable Solutions</fullName>
                </value>
                <value>
                    <fullName>Receivable Solutions</fullName>
                </value>
                <value>
                    <fullName>Liquidity Solutions</fullName>
                </value>
                <value>
                    <fullName>Fraud Solutions</fullName>
                </value>
                <value>
                    <fullName>Business Checking</fullName>
                </value>
                <value>
                    <fullName>Treasury Deposits</fullName>
                </value>
                <value>
                    <fullName>Contract Services</fullName>
                </value>
                <value>
                    <fullName>Public Funds</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Checking</fullName>
                </value>
                <value>
                    <fullName>Savings</fullName>
                </value>
                <value>
                    <fullName>CDs</fullName>
                </value>
                <value>
                    <fullName>IRAs</fullName>
                </value>
                <value>
                    <fullName>HSAs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TM_Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>TM_Product_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Commercial Checking</fullName>
                </value>
                <value>
                    <fullName>Community Checking</fullName>
                </value>
                <value>
                    <fullName>Small Business Checking</fullName>
                </value>
                <value>
                    <fullName>Public Funds Non-Interest Bearing Checking</fullName>
                </value>
                <value>
                    <fullName>Public Funds Interest Bearing Checking</fullName>
                </value>
                <value>
                    <fullName>CDARS</fullName>
                </value>
                <value>
                    <fullName>ICS</fullName>
                </value>
                <value>
                    <fullName>Repurchase Agreement</fullName>
                </value>
                <value>
                    <fullName>Multi User</fullName>
                </value>
                <value>
                    <fullName>EDI Addenda Translation</fullName>
                </value>
                <value>
                    <fullName>BAI File Download</fullName>
                </value>
                <value>
                    <fullName>BAI SFTP</fullName>
                </value>
                <value>
                    <fullName>ACH Origination</fullName>
                </value>
                <value>
                    <fullName>ACH Third Party Sender</fullName>
                </value>
                <value>
                    <fullName>Wire Transmission</fullName>
                </value>
                <value>
                    <fullName>Business BillPay</fullName>
                </value>
                <value>
                    <fullName>Credit Card Small Business</fullName>
                </value>
                <value>
                    <fullName>Credit Card Corporate</fullName>
                </value>
                <value>
                    <fullName>Credit Card Purchasing</fullName>
                </value>
                <value>
                    <fullName>RDC Low-Speed Scanner</fullName>
                </value>
                <value>
                    <fullName>RDC Hi-Speed Scanner</fullName>
                </value>
                <value>
                    <fullName>RDC Mobile</fullName>
                </value>
                <value>
                    <fullName>Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Payment Portal U-Pay</fullName>
                </value>
                <value>
                    <fullName>Payment Portal Autobooks</fullName>
                </value>
                <value>
                    <fullName>Payment Portal I-Collect</fullName>
                </value>
                <value>
                    <fullName>Lockbox Remote</fullName>
                </value>
                <value>
                    <fullName>Lockbox Retail</fullName>
                </value>
                <value>
                    <fullName>Lockbox Healthcare</fullName>
                </value>
                <value>
                    <fullName>Single Sweep</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TM_AddProductsController.cls
/**
 * @description TM_AddProductsController
 */ 
public without sharing class TM_AddProductsController {
    /**
     * @description getProductDetails description
     * @return   return description
     */
    @AuraEnabled(cacheable=true)
    public static List<PricebookEntry> getProductDetails(String oppId){
        try{
            // Get Opportunity recordtype to distinguish the product
            List<Opportunity> oppLst = [SELECT Id, RecordType.Name FROM Opportunity WHERE Id =: oppId];
            String oppProductType = 'Treasury Solutions';
            if ( oppLst.size() > 0 && oppLst[0].RecordType.Name == 'Track Deposit Pipeline') {
                oppProductType = 'Business Deposits';
            }
            // system.debug('check data' + oppProductType);

            List<PricebookEntry> productsList = [SELECT Name,Pricebook2Id,Product2Id,UnitPrice,Product2.Name,Product2.TM_Product_Line__c,Product2.TM_Product_Type__c,Product2.TM_Product__c,Product2.TM_Order_Number__c FROM PricebookEntry WHERE Product2.TM_Product_Line__c = :oppProductType ORDER BY Product2.TM_Order_Number__c];
            return productsList;
        } catch(Exception ex) {
            throw new AuraHandledException(System.Label.TM_StdErrorMessage);
        }
    }

    /**
     * @description saveOpportunityItems description
     * @param  oppId    oppId description
     * @param  oppItems oppItems description
     */ 
    // @AuraEnabled(cacheable=true)
    @AuraEnabled(Cacheable=false)
    public static void saveOpportunityItems(String oppId, List<OpportunityLineItem> oppItems){
        Savepoint sp = Database.setSavepoint();
        try {
            // Opportunity list
            List<Opportunity> oppLst = [SELECT Id, Pricebook2Id FROM Opportunity WHERE Id =: oppId];
            if (oppLst.size() > 0 && oppLst[0].Pricebook2Id != null) {
                for (OpportunityLineItem item : oppItems) {
                    item.OpportunityId = oppId;
                }
                insert oppItems;
            } else {
                if(Test.isrunningtest()) {
                    Id pricebookId = Test.getStandardPricebookId();//Return getStandardPricebookId 
                    oppLst[0].Pricebook2Id = pricebookId;
                } else {
                    Pricebook2 pricebookId = [SELECT Id FROM Pricebook2 WHERE Name = 'Standard Price Book'][0]; 
                    oppLst[0].Pricebook2Id = pricebookId.Id;
                }
                // Pricebook2 pricebookId = [SELECT Id FROM Pricebook2 WHERE Name = 'Standard Price Book'][0]; 
                // oppLst[0].Pricebook2Id = pricebookId.Id;
                
                update oppLst;
                for (OpportunityLineItem item : oppItems) {
                    item.OpportunityId = oppId;
                }
                insert oppItems;
            }
        } catch (Exception ex) {
            Database.rollback(sp);
            // throw exception
            throw new AuraHandledException(System.Label.TM_StdErrorMessage);
        } 
    }
}