objects/Treasury_Goals__c.object
<CustomObject>
    <fields>
        <fullName>TM_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TM_Fiscal_Year__c</fullName>
        <label>Fiscal Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
                <value>
                    <fullName>2026</fullName>
                </value>
                <value>
                    <fullName>2027</fullName>
                </value>
                <value>
                    <fullName>2028</fullName>
                </value>
                <value>
                    <fullName>2029</fullName>
                </value>
                <value>
                    <fullName>2030</fullName>
                </value>
                <value>
                    <fullName>2031</fullName>
                </value>
                <value>
                    <fullName>2032</fullName>
                </value>
                <value>
                    <fullName>2033</fullName>
                </value>
                <value>
                    <fullName>2034</fullName>
                </value>
                <value>
                    <fullName>2035</fullName>
                </value>
                <value>
                    <fullName>2036</fullName>
                </value>
                <value>
                    <fullName>2037</fullName>
                </value>
                <value>
                    <fullName>2038</fullName>
                </value>
                <value>
                    <fullName>2039</fullName>
                </value>
                <value>
                    <fullName>2040</fullName>
                </value>
                <value>
                    <fullName>2041</fullName>
                </value>
                <value>
                    <fullName>2042</fullName>
                </value>
                <value>
                    <fullName>2043</fullName>
                </value>
                <value>
                    <fullName>2044</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TM_Treasury_Solutions_Officer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Treasury Sales Officer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Treasury_Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Treasury Goals</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Treasury Goals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Treasury Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TM_TreasuryGoalHandler.cls
/**
 * @description  Handler for Treasury Goals trigger
 */ 
public with sharing class TM_TreasuryGoalHandler {
    /**
     * @description beforeUpsertTreasuryGoals description
     * @param  treasuryGoals treasuryGoals description
     */ 
    public void beforeUpsertTreasuryGoals(List<Treasury_Goals__c> treasuryGoals, Map<Id,Treasury_Goals__c> oldMap){
        
        List<Treasury_Goals__c> activedTreasuryGoals = [SELECT Id, TM_Fiscal_Year__c, TM_Treasury_Solutions_Officer__c  FROM Treasury_Goals__c WHERE TM_Active__c = true];
        // if(activedTreasuryGoals.size() <= 0){
        //     return;
        // }
        for (Treasury_Goals__c treasuryGoal : treasuryGoals) {
            if (treasuryGoal.TM_Active__c && (treasuryGoal.Id == null || !oldMap.get(treasuryGoal.Id).TM_Active__c || oldMap.get(treasuryGoal.Id).TM_Treasury_Solutions_Officer__c  != treasuryGoal.TM_Treasury_Solutions_Officer__c ) ) {
                Boolean isHasActivedGoal = checkActivedGoals(treasuryGoal.Id,treasuryGoal.TM_Treasury_Solutions_Officer__c , treasuryGoal.TM_Fiscal_Year__c, activedTreasuryGoals);
                if (isHasActivedGoal) {
                    treasuryGoal.TM_Treasury_Solutions_Officer__c .addError(System.label.TM_Treasury_Goals_ErrorMessage);
                }
            }
        }
    }

    /**
     * @description checkActivedGoals description
     * @param  goalId       goalId description
     * @param  rmId         rmId description
     * @param  year         year description
     * @param  activedGoals activedGoals description
     * @return              return description
     */ 
    public Boolean checkActivedGoals(Id goalId, Id rmId, String year, List<Treasury_Goals__c> activedGoals){
        for (Treasury_Goals__c treasuryGoal : activedGoals) {
            if (goalId == null && treasuryGoal.TM_Treasury_Solutions_Officer__c  == rmId && treasuryGoal.TM_Fiscal_Year__c == year) {
                return true;
            }else if (treasuryGoal.TM_Treasury_Solutions_Officer__c  == rmId && treasuryGoal.TM_Fiscal_Year__c == year && treasuryGoal.Id != goalId) {
                return true;
            }
        }
        return false;
    }
}